---
- name: Ensure task lib folder exists
  ansible.builtin.file:
    path: "{{ task_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 'u=rwx,go=rx'
  become: true

- name: Download task archive
  ansible.builtin.get_url:
    url: "{{ task_download_url }}"
    dest: /tmp/task.tar.gz
    mode: 'u=rw,go=r'
    checksum: "{{ task_archive_checksum }}"
  changed_when: false

- name: Extract task archive
  ansible.builtin.unarchive:
    src: /tmp/task.tar.gz
    dest: "{{ task_install_path }}"
    creates: "{{ task_install_path }}/task"
    owner: root
    group: root
    remote_src: true
  become: true

- name: Remove task archive
  ansible.builtin.file:
    path: /tmp/task.tar.gz
    state: absent
  changed_when: false

- name: Create task symlink
  ansible.builtin.file:
    src: "{{ task_install_path }}/task"
    dest: "{{ task_bin }}"
    owner: root
    group: root
    state: link
    force: true
  become: true

- name: Stat task binary checksum
  ansible.builtin.stat:
    path: "{{ task_install_path }}/task"
    checksum_algorithm: sha256
  register: st

- name: Verify task binary checksum
  ansible.builtin.fail:
    msg: "Checksum verification failed, was the Task binary modified?"
  when: st.stat.checksum != task_binary_checksum
