---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "include vars"
      include_vars:
        file: ../../defaults/main.yml
    - name: Check Task version
      command: task --version
      register: output
    - name: Assert that Task is installed
      assert:
        that:
          - "'Task version: v{{ task_version }}' in output.stdout"
