---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "include vars"
      ansible.builtin.include_vars:
        file: ../../defaults/main.yml
    - name: Check Task version
      ansible.builtin.command: task --version
      register: output
    - name: Assert that Task is installed
      ansible.builtin.assert:
        that:
          - "'Task version: v{{ task_version }}' in output.stdout"
